### ISSUE TITLE
Issues with building

### ISSUE THREAD

**Issue by StickyChannel92** [TakuikaNinja/smb1-bugfix#1]
![image](https://github.com/user-attachments/assets/11a75010-3c3a-4339-8839-47ec9b7c3f0f)
![image](https://github.com/user-attachments/assets/85f1b794-ca88-4af6-8662-60f0513c4d5b)

Attempting to build.sh the rom in WSL Ubuntu gives an error that asm6f is not a directory or file. As this is a bash script and not a Windows script, I needed WSL. Inserting asm6f.c into the main directory gives out the "Permission denied" error. Am I missing something? I have the CHR file, I just need help on how to build the ROM.

**Comment by TakuikaNinja** [comment]
The build script currently assumes that the asm6f binary is placed in the same directory due to it being invoked as `./asm6f`. Perhaps it should be changed so that asm6f is invoked from $PATH instead: `asm6f`. 
A better long-term solution would probably be to use a Makefile for cross-platform ease of use.

**Comment by TakuikaNinja** [comment]
They should be addressed now. Please check on your end.

**Comment by StickyChannel92** [comment]
Can I get a little help here? What build of asm6f do I use and where can I find it? How do I set it up? There are no clear instructions on the readme on my end.

The terminal now says that asm6f is not a command, even though asm6f.c is in the directory.

**Comment by TakuikaNinja** [comment]
That's the C source code. You need to compile a binary executable using the Makefile in asm6f's repository: https://github.com/freem/asm6f
`make` followed by `sudo make install` will build and place it in a directory within $PATH.

**Comment by StickyChannel92** [comment]
![image](https://github.com/user-attachments/assets/d6cea023-9ffb-4079-9d7e-532884b07d06)
I get some weird error with something called "gcc". I installed make using `sudo install make` and typing `make` in the asm6f directory gives errors.

So I installed gcc with a few 404 errors and get this:
![image](https://github.com/user-attachments/assets/a84e82c2-4e16-476c-91ff-2e4d77edd296)

Is it OK if you provide the bugfix project IPS patch so that I can patch up the vanilla SMB1 rom? I have spent days trying to figure out how to prepare this game for playability.

**Comment by TakuikaNinja** [comment]
You need to install all the GNU build tools and libraries. This is done on Ubuntu by using its package manager: `sudo apt install build-essential`

**Comment by StickyChannel92** [comment]
![image](https://github.com/user-attachments/assets/95a938ce-f73f-4a31-95ba-6e59c13a065b)
I figured out how to compile asm6f, but it's still saying the command is not found, even though its in the same directory as the repo. I even copied the binary into my user folder (~) and that didn't help.

**Comment by TakuikaNinja** [comment]
Oh, I forgot there was no install rule for asm6f...
In that case, you can manually move the binary to `/usr/bin/` or `/usr/local/bin/`
I'll amend the build scripts later so they check where asm6f is installed.

**Comment by StickyChannel92** [comment]
![image](https://github.com/user-attachments/assets/c118273f-8e33-4a3f-af96-7e156a696f42)
I still get the error where permission is denied after moving the file, even when using sudo.

**Comment by TakuikaNinja** [comment]
Have you tried running the build scripts without `sudo`? Root permissions aren't needed for this.

**Comment by TakuikaNinja** [comment]
Also, could you check the permissions set on asm6f? `ls -l /usr/local/bin/asm6f` will show the permission bits. 
The execute (x) permission needs to be set for owner/group/others (`-??x??x??x`), at the very least. 
If they aren't set, use `sudo chmod a+x /usr/local/bin/asm6f` to set them.

**Comment by StickyChannel92** [comment]
It almost made it, but it is missing a Python script called sssfix.py.
![image](https://github.com/user-attachments/assets/1c0c0abc-1daa-4f05-a40a-541b3b49c337)

**Comment by TakuikaNinja** [comment]
That's expected - the script is linked in the readme for the main branch but not actually included. Full link: https://github.com/pinobatch/240p-test-mini/blob/master/nes/tools/sssfix.py 
I chose not to directly host it in the repo because of the commented notes claiming it was unfinished, and because it doesn't have a standalone release yet.

**Comment by StickyChannel92** [comment]
![image](https://github.com/user-attachments/assets/5f514e73-1bc7-4640-a288-e9b08236bae5)
I put the script in the directory and it's still saying that permission is denied. Also says that when in /usr/bin AND when its _x_ permission is set.

**Comment by TakuikaNinja** [comment]
The python script stays in the repo's directory. It should work with the execute permissions set. 
If that doesn't work, then you probably don't have python3 installed.

**Comment by StickyChannel92** [comment]
![image](https://github.com/user-attachments/assets/be11d4d0-a9de-40b8-b8c4-33edb577481c)
It works! Thanks so much for the help!
I had to install flips and libgtk-3-dev as well for it to work.
The only issue I can find is that the Goombas look like this:
![image](https://github.com/user-attachments/assets/98b6b831-ebad-4ba0-bd89-c7ca622ec2ea)
What do I need to edit in the hex editor to fix this?

**Comment by TakuikaNinja** [comment]
There's an included IPS patch you need to apply to the CHR file. That contains all the graphics changes.

**Comment by StickyChannel92** [comment]
Thank you so much! My issue has been resolved and I can enjoy playing this hack. :]
Closing issue now.
I might make some instructions for beginners if you're alright with that.

**Comment by TakuikaNinja** [comment]
I don't really mind, as long as you don't provide a location to obtain the CHR data. I intend on releasing the standalone BPS patch for this eventually.

**Comment by StickyChannel92** [comment]
[smb1-bugfix.txt](https://github.com/user-attachments/files/17301664/smb1-bugfix.txt)

**Comment by TakuikaNinja** [comment]
- The ROM is compiled and output to the same directory as the patch ("smb1.nes" or "smb1.fds"), so there's no need to use the patch file outside of the distribution process. 
- The final patch output is in the BPS format, not IPS. It's this way due to data being shifted around. 

Otherwise, it seems fine.
