### ISSUE TITLE
Shadow Bowser

### ISSUE THREAD

**Issue by Vutshi** [TakuikaNinja/smb1-bugfix#4]
Someone invisible gets hit by Mario's last fireball after the fake Bowser is defeated:

![bug3](https://github.com/user-attachments/assets/f425eced-c5bf-43f9-8d92-640f911b9ee2)

**Comment by TakuikaNinja** [comment]
I guess I never saw that one in the original until now.

**Comment by Vutshi** [comment]
That was fast!
