### ISSUE TITLE
Moving Platforms Don't Block Mario

### ISSUE THREAD

**Issue by Vutshi** [TakuikaNinja/smb1-bugfix#5]
Moving platforms don't obstruct Mario, reducing the challenge:

![bug4](https://github.com/user-attachments/assets/5fbe94d5-85ee-4c25-859f-8e55a7bcaf5e)

**Comment by TakuikaNinja** [comment]
While it does make those particular underwater sections easier, that is an intentional change meant to reflect the Mario Maker games. Not changing.

**Comment by Vutshi** [comment]
Could the changes affecting gameplay, like non-blocking platforms and excessive lives, be made optional?

**Comment by TakuikaNinja** [comment]
I'd rather not do that as then we'd have to maintain/test several code variations. There's no guarantee that all of the code would fit into the remaining space, either.
